name: Azure Login Test
on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types: [opened, synchronize, reopened]
env:
  TF_VERSION: '1.5.0'
  ARM_CLIENT_ID: ${{ secrets.AZ_SERVICE_PRINCIPAL }}
  ARM_CLIENT_SECRET: ${{ secrets.AZ_SP_PASSWORD }}
  ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZ_SUBSCRIPTION_ID}}
jobs:
  AZ_login_and_Terraform_Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login via Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure Login
        run: |
          echo "ðŸ” Verifying Azure login..."
          if ! az account show; then
            echo "âŒ Failed to verify Azure login. Please check credentials or login step." >&2
            exit 1
          fi
          echo "âœ… Azure login verified. Subscription:"
          az account show --output table


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
  
      - name: terraform-init # terraform Init
        env:
          TF_VARS_rg_name: ${{vars.TF_VARS_rg_name}}
          TF_VARS_blobstorage: ${{vars.TF_VARS_blobstorage}}
          TF_VARS_blobcontainer: ${{vars.TF_VARS_blobcontainer}}
        run: |
          chmod +x ./create_backend_config.sh
          ./create_backend_config.sh
      
      - name: Debug path before upload
        run: |
          echo "Current dir: $(pwd)"
          ls -la
          ls -la .terraform
          ls -la .terraform.lock.hcl

      - name: Upload Terraform Init Data
        uses: actions/upload-artifact@v4
        with:
          name: terraform-init
          path: |
            .terraform/**
            .terraform.lock.hcl



        
