name: Azure Login Test
on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types: [opened, synchronize, reopened]
env:
  TF_VERSION: '1.5.0'
jobs:
  test-azure-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Azure CLI login # i have leveraged Azure Log in as az github action login is giving the issue 
      #   env:
      #     AZ_CLIENT_ID: ${{ secrets.AZ_SERVICE_PRINCIPAL }}
      #     AZ_CLIENT_SECRET: ${{ secrets.AZ_SP_PASSWORD }}
      #     AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      #   run: |
      #     az login --service-principal -u $AZ_CLIENT_ID -p $AZ_CLIENT_SECRET --tenant $AZ_TENANT_ID
      #     set -e
      #     echo "Attempting to login to Azure..."
      #     if ! az login --service-principal -u "$AZ_CLIENT_ID" -p "$AZ_CLIENT_SECRET" --tenant "$AZ_TENANT_ID" > /dev/null 2>&1; then
      #       echo "âŒ Azure login failed. Please check your service principal credentials." >&2
      #       exit 1
      #     fi
      #     echo "âœ… Azure login successful."


      - name: Azure Login via Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZ_SERVICE_PRINCIPAL }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZ_SP_PASSWORD }}
          auth-type: SERVICE_PRINCIPAL

      - name: Verify Azure Login
        run: |
          echo "ðŸ” Verifying Azure login..."
          if ! az account show; then
            echo "âŒ Failed to verify Azure login. Please check credentials or login step." >&2
            exit 1
          fi
          echo "âœ… Azure login verified. Subscription:"
          az account show --output table


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
  
      - name: Terraform init # terraform Init
        env:
          TF_VARS_rg_name: ${{vars.TF_VARS_rg_name}}
          TF_VARS_blobstorage: ${{vars.TF_VARS_blobstorage}}
          TF_VARS_blobcontainer: ${{vars.TF_VARS_blobcontainer}}
        run: |
          chmod +x ./create_backend_config.sh
          ./create_backend_config.sh

      - name: Upload Terraform Init Data
        uses: actions/upload-artifact@v4
        with:
          name: terraform-init
          path: |
            .terraform
            .terraform.lock.hcl



        
